-- Oracle 1일차
-- 제약조건 없는 데이블
CREATE TABLE USER_NO_CONSTRAINT(
    USER_NO NUMBER,
    USER_ID VARCHAR2(20),
    USER_PWD VARCHAR2(30),
    USER_NAME VARCHAR2(30),
    USER_GENDER VARCHAR2(10),
    USER_PHONE VARCHAR2(30),
    USER_EMAIL VARCHAR2(50)
);

DESC USER_NO_CONSTRAINT;

INSERT INTO USER_NO_CONSTRAINT
VALUES(1, 'olauser01', 'pass01', '일용자', '남', '01012341234', 'olauser01@ola.com');
INSERT INTO USER_NO_CONSTRAINT
VALUES(2, 'olauser02', 'pass02', '이용자', '남', '01012341234', 'olauser02@ola.com');
INSERT INTO USER_NO_CONSTRAINT
VALUES(3, null, 'pass03', '삼용자', '남', '01012341234', 'olauser03@ola.com');



SELECT * FROM USER_NO_CONSTRAINT;

DELETE FROM USER_NO_CONSTRAINT WHERE USER_NO = 1;

-- NOT NULL 제약조건 
CREATE TABLE USER_CONSTRAINT_NOTNULL(
    USER_NO NUMBER,
    USER_ID VARCHAR2(20) NOT NULL,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    USER_GENDER VARCHAR2(10),
    USER_PHONE VARCHAR2(30),
    USER_EMAIL VARCHAR2(50)
);

SELECT * FROM USER_CONSTRAINT_NOTNULL;

INSERT INTO USER_CONSTRAINT_NOTNULL 
VALUES (1, 'OLAUSER01', 'PASS01', '일용자', '님', '01022223333', 'OLAUSER01@.OLA.COM);

-- 
CREATE TABLE USER_CONSTRANINT_UNIQUE(
    USER_NO NUMBER,
    USER_ID VARCHAR2(20) UNIQUE,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    USER_GENDER VARCHAR2(10),
    USER_PHONE VARCHAR2(30),
    USER_EMAIL VARCHAR2(50)
);

INSERT INTO USER_CONSTRAINT_UNIQUE
VALUES(1, 'olauser01', 'pass01', '일용자', '남', '01012341234', 'olauser01@ola.com');
INSERT INTO USER_CONSTRAINT_UNIQUE
VALUES(2, 'olauser02', 'pass02', '이용자', '남', '01012341234', 'olauser02@ola.com');
INSERT INTO USER_CONSTRAINT_UNIQUE
VALUES(3, null, 'pass03', '삼용자', '남', '01012341234', 'olauser03@ola.com');
INSERT INTO 

-- 오라클 1일차, 쿼리문 연습(CREATE, INSERT)
-- 테이블명 : DEPARTMENT
-- 컬럼 : DEPT_ID, DEPT_TITLE, LOCATION_ID
-- 자료형: CHAR(2), VARCHAR2(35), CHAR(2)
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT(
    DEPT_ID CHAR(2),
    DEPT_TITLE VARCHAR2(35),
    LOCATION_ID CHAR(2)
);

COMMENT ON COLUMN DEPARTMENT.DEPT_ID IS '부서코드';
COMMENT ON COLUMN DEPARTMENT.DEPT_TITLE IS '부서명';
COMMENT ON COLUMN DEPARTMENT.LOCATION_ID IS '지역코드';

INSERT INTO DEPARTMENT VALUES('D1', '인사관리부', 'L1');
INSERT INTO DEPARTMENT VALUES('D2', '회계관리부', 'L1');
INSERT INTO DEPARTMENT VALUES('D3', '마케팅부', 'L1');
INSERT INTO DEPARTMENT VALUES('D4', '국내영업부', 'L1');
INSERT INTO DEPARTMENT VALUES('D5', '해외영업1부', 'L2');
INSERT INTO DEPARTMENT VALUES('D6', '해외영업2부', 'L3');
INSERT INTO DEPARTMENT VALUES('D7', '해외영업3부', 'L4');
INSERT INTO DEPARTMENT VALUES('D8', '기술지원부', 'L5');
INSERT INTO DEPARTMENT VALUES('D9', '총무부', 'L1');


-- 테이블명 : EMPLOYEE
--이름         널? 유형           
------------ -- ------------ 
--EMP_ID        VARCHAR2(3)  
--EMP_NAME      VARCHAR2(20) 
--EMP_NO        CHAR(14)     
--EMAIL         VARCHAR2(25) 
--PHONE         VARCHAR2(12) 
--DEPT_CODE     CHAR(2)      
--JOB_CODE      CHAR(2)      
--SAL_LEVEL     CHAR(2)      
--SALARY        NUMBER       
--BONUS         NUMBER       
--MANAGER_ID    VARCHAR2(3)  
--HIRE_DATE     DATE         
--ENT_DATE      DATE         
--ENT_YN        CHAR(1)
CREATE TABLE EMPLOYEE(
    EMP_ID VARCHAR2(3),
    EMP_NAME VARCHAR2(20),
    EMP_NO CHAR(14),
    EMAIL VARCHAR2(25),
    PHONE VARCHAR2(12),
    DEPT_CODE CHAR(2),
    JOB_CODE CHAR(2),
    SAL_LEVEL CHAR(2),
    SALARY NUMBER,
    BONUS NUMBER,
    MANAGER_ID VARCHAR2(3),
    HIRE_DATE DATE,
    ENT_DATE DATE,
    ENT_YN CHAR(1)
);
DROP TABLE EMPLOYEE;

COMMENT ON COLUMN EMPLOYEE.EMP_ID IS '사원번호';
COMMENT ON COLUMN EMPLOYEE.EMP_NAME IS '직원명';
COMMENT ON COLUMN EMPLOYEE.EMP_NO IS '주민등록번호';
COMMENT ON COLUMN EMPLOYEE.EMAIl IS '이메일';
COMMENT ON COLUMN EMPLOYEE.PHONE IS '전화번호';
COMMENT ON COLUMN EMPLOYEE.DEPT_CODE IS '부서코드';
COMMENT ON COLUMN EMPLOYEE.JOB_CODE IS '직급코드';
COMMENT ON COLUMN EMPLOYEE.SAL_LEVEL IS '급여등급';
COMMENT ON COLUMN EMPLOYEE.SALARY IS '급여';
COMMENT ON COLUMN EMPLOYEE.BONUS IS '보너스율';
COMMENT ON COLUMN EMPLOYEE.MANAGER_ID IS '관리자사번';
COMMENT ON COLUMN EMPLOYEE.HIRE_DATE IS '입사일';
COMMENT ON COLUMN EMPLOYEE.ENT_DATE IS '퇴사일';
COMMENT ON COLUMN EMPLOYEE.ENT_YN IS '퇴직여부';

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE
, DEPT_CODE, JOB_CODE, SAL_LEVEL, SALARY, BONUS, MANAGER_ID
, HIRE_DATE, ENT_DATE, ENT_YN)
VALUES('100', '일용자', '991211-1234123', 'olauser01@ola.com'
, '01022334455', 'D1', 'J1', 'S1', 6000000, 0.5, '101', SYSDATE, SYSDATE, 'N');

INSERT INTO EMPLOYEE
VALUES('101', '이용자', '001101-3123123', 'olauser02@ola.com'
, '01022223333', 'D2', 'J2', 'S2', 7000000, 0.3, '101', SYSDATE, SYSDATE, 'N');


SELECT * FROM EMPLOYEE;
COMMIT; 
ROLLBACK;